name: CI

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run a check script
      run: bash scripts/check.sh
      with:
        github-token: ${{ secrets.TOKEN }}
